page_lang_verify = "Images"
search_term = "red"
verify_search_page = "resultStats"
verify_result_text = "Red (2010 film) - Wikipedia"
long_search_term = "test automation"
no_result_term = "adasfdasf ssdjfhksdahfk sdafjdshafkjdsahfkjdshafkhsadkfhdsakjfhkadsjhfs"
no_result_text = "did not match any documents."
